image: zmlccf/maven-aliyun:3.6.3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"
  CI_REGISTRY: "192.168.1.111:8089"
  CI_DEPLOY_USER: "admin"
  CI_DEPLOY_PASSWORD: "Harbor12345"
  CONTAINER: "abc/hello-spring"
  TAG: "v0.2"


stages:
  - package
  - build

maven-package:
  image: zmlccf/maven-aliyun:3.6.3-jdk-8
  tags:
    - maven
  stage: package
  script:
    - pwd
    - sh build.sh
    - ls -lah
    - sleep 5
  artifacts:
    paths:
      - target/*.jar
  

docker-build:
  image: docker:stable
  tags:
    - docker
  stage: build
  script:
    - echo "Building Dockerfile-based application..."
    - pwd
    - ls -lah
    - docker build -t $CI_REGISTRY/$CONTAINER:$TAG .
    - docker images
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD http://$CI_REGISTRY
    - docker push $CI_REGISTRY/$CONTAINER:$TAG 
